<?php
/**
 * Administrator repository.
 * User: YingQuan-han
 * Date: 2018/11/1
 * Time: 14:50
 */

namespace App\Repositories;


use App\Models\Admin;

class AdminRepository extends Repository
{
    public function model()
    {
        // TODO: Implement model() method.
        return Admin::class;
    }


    public function findBy($id)
    {
        return parent::findBy($id); // TODO: Change the autogenerated stub
    }


    /**
     * Finding administrator login data.
     *
     * @param $username
     * @return mixed
     */
    public function findByAdminLogin($username)
    {
        return $this->model->orWhere('name', trim($username))->orWhere('email', trim($username))->first();
    }


    /**
     * Get all administrator data
     *
     * @return mixed
     */
    public function allByAdmin()
    {
        return $this->model
            ->orderBy('created_at', 'asc')
            ->get()
            ->toArray();
    }


    /**
     * Find members associated with roles.
     *
     * @param $roleId
     * @return mixed
     */
    public function findRoleByAdmin($roleId)
    {
        return $this->model
            ->whereHas('belongsToManyRole', function ($query) use ($roleId){
                $query->where('id', $roleId);
            })
            ->orderBy('created_at', 'asc')
            ->get()
            ->toArray();
    }
}