<?php
/**
 * Administrator repository.
 * User: YingQuan-han
 * Date: 2018/11/1
 * Time: 14:50
 */

namespace App\Repositories;


use App\Models\Admin;

class AdminRepository extends Repository
{
    public function model()
    {
        // TODO: Implement model() method.
        return Admin::class;
    }


    public function findBy($id)
    {
        return parent::findBy($id); // TODO: Change the autogenerated stub
    }


    /**
     * Finding administrator login data.
     * @param $username
     * @return mixed
     */
    public function findByAdminLogin($username)
    {
        return $this->model->orWhere('name', trim($username))->orWhere('email', trim($username))->first();
    }
}